### ISSUE TITLE
Cannot instantiate abstract class Teepluss\\Theme\\Widget

### ISSUE THREAD

**Issue by z2z** [teepluss/laravel-theme#102]
While using laravel-ide-helper with branch for laravel 4 (v1.x)

php artisan ide-helper:meta

{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","me
ssage":"Cannot instantiate abstract class Teepluss\\Theme\\Widget","file":"D:\\n
q\\ips\\NQ\\xampp\\htdocs\\sips\\vendor\\teepluss\\theme\\src\\Teepluss\\Theme\\
ThemeServiceProvider.php","line":100}}

**Comment by j-a-p-dev** [comment]
Hello you closed this issue but you didn't fix this issue for Laravel 4 (1.x)

**Comment by teepluss** [comment]
Sorry, I’ve fixed for Laravel 5.0, so now I already fix for 4.2 too.



On June 9, 2558 BE at 12:36:09 AM, j-a-p-dev (notifications@github.com) wrote:

Hello you closed this issue but you didn't fix this issue for Laravel 4 (1.x)
