### ISSUE TITLE
Using theme global, need to implement Dependency injection in all subclass?

### ISSUE THREAD

**Issue by nhim175** [teepluss/laravel-theme#109]
I followed the example in Using theme global section.

Whenever I create a subclass of BaseController class, seems like I have to do something like this:

	class AnotherController extends BaseController {
	  public function __construct(Theme $theme) {
	  	parent::__construct($theme);
	  	...
	  }
	}
	
Is there any better way?

**Comment by teepluss** [comment]
~~~php


namespace App\Http\Controllers\Demo;

use App\Http\Controllers\Controller;
use Teepluss\Theme\Contracts\Theme;

class ThemeController extends Controller
{
    public function __construct(Theme $theme)
    {
        $this->theme = $theme->uses('default');
    }

    public function getIndex()
    {
        return $this->theme->scope('theme.index')->render();
    }
}
~~~
