### ISSUE TITLE
Support Laravel v7+

### ISSUE THREAD

**Issue by DevynCJohnson** [teepluss/laravel-theme#156]
Your software is amazing. I thank you for your work.

However, I am needing to update my project to Laravel v7.12. However, your Laravel plugin/package does not support Laravel v7.12. Your software is amazing and I do not want to have to go through Tepluss-Laravel-Theme withdrawal nor have to find an alternative.

**Comment by C0kkie** [comment]
Try that https://github.com/imajkumar/laravel-theme-management

**Comment by DevynCJohnson** [comment]
Awesome, thanks!
