### ISSUE TITLE
'assetUrl' is not overwriting the new value at concrete theme config file

### ISSUE THREAD

**Issue by ensensis** [teepluss/laravel-theme#53]
Ok, I am adding a css file to the theme like:

```
'events' => array(
    'before' => function($theme)
    {
        $theme->asset()->add('style', 'css/style.css');
```

In the `app\config\packages\teepluss\theme` I have this:

```
'assetUrl' => URL::to('/'),
```

I have tried to overwrite this value at `public\themes\default`

```
'assetUrl' => URL::to('/public/themes/default/'),
```

However, in the html final render the css url stills being `localhost/css/style.css`, and this is incorrect, because the expected value should be `localhost/public/themes/default/css/style.css`.

**Comment by akizor** [comment]
@ensensis At L5.2 for me worked setting 'assetUrl' => env('APP_URL', 'http://localhost/my_public_directory') in theme config. This way, when moving project around, everything will stay updated.
