### ISSUE TITLE
Getting this error..

### ISSUE THREAD

**Issue by ntuple** [teepluss/laravel-theme#88]
Call to undefined method Teepluss\Theme\Theme Service Provider::published()

Just went throught the code publised function is no were..

**Comment by rajlaksh** [comment]
Same here i got this Fatal Error too.

**Comment by ntuple** [comment]
If you are using Laravel 4 following should be, in composer.json file 
~~~~
"require": {
                "teepluss/theme": "~1"
},
~~~
