### ISSUE TITLE
ErrorException in Theme.php line 899:

### ISSUE THREAD

**Issue by assoft** [teepluss/laravel-theme#89]
Laravel 5

HomeController =>

use Teepluss\Theme\Theme;

class HomeController extends Controller
{
protected $theme;

	public function __construct(Theme $theme)
	{
		$this->theme = $theme;
		$this->theme->uses('default')->layout('default');
	}

	public function index()
	{
		return $this->theme->of('home')->render(); 
               //return \Theme::of('home')->render();
	}
}
Error => 

ErrorException in Theme.php line 899:
Undefined index: content (View: /Users/assoft/Sites/l5/public/themes/default/layouts/default.blade.php)

themes default.blade.php => 

       <title>{!! Theme::get('title') !!}</title>
        <meta charset="utf-8">
        <meta name="keywords" content="{!! Theme::get('keywords') !!}">
        <meta name="description" content="{!! Theme::get('description') !!}">
        {!! Theme::asset()->styles() !!}
        {!! Theme::asset()->scripts() !!}
    </head>
    <body>
        {!! Theme::partial('header') !!}
        <div class="container">
            {!! Theme::content() !!}
        </div>
        {!! Theme::partial('footer') !!}
        {!! Theme::asset()->container('footer')->scripts() !!}

but if not method injection then no error

**Comment by assoft** [comment]
Sorry my bad english.

**Comment by teepluss** [comment]
Please use Theme from facade 

~~~php
<?php namespace App\Http\Controllers\Demo;

use App\Http\Controllers\Controller;
use Theme;

class ThemeController extends Controller {

    public function __construct()
    {
        $this->theme = Theme::uses('default')->layout('mobile');
    }

    public function getIndex()
    {
        return $this->theme->of('demo.theme.index')->render();
    }

}
~~~
